### page_admin.py ###

import streamlit as st
import msc_lib as msc
import msc_viz as viz
import msc_sim as sim
import time
import pandas as pd
import json
import msc_db as db 

def render_admin_dashboard():
    st.markdown("## 👁️ Overseer Terminal")
    st.caption("v75.5 Arrival / System Status: ONLINE")
    
    # 获取数据
    all_users = msc.get_all_users("admin")
    # 获取更多节点以供监控
    global_nodes = msc.get_global_nodes() 
    
    # === 📊 数据预处理 ===
    # 1. 用户统计
    user_stats = {}
    if all_users:
        for u in all_users:
            user_stats[u['username']] = {'nodes': 0, 'total_score': 0.0}
            
    # 2. 节点流数据准备
    node_stream_data = []
    
    if global_nodes:
        for n in global_nodes:
            # 统计用户数据
            un = n['username']
            if un in user_stats:
                user_stats[un]['nodes'] += 1
                try: user_stats[un]['total_score'] += float(n.get('logic_score', 0))
                except: pass
            
            # 准备监控流表格数据
            # 解析时间
            created_time = n.get('created_at', '')[:16].replace('T', ' ')
            
            node_stream_data.append({
                "Time": created_time,
                "User": un,
                "Care Point": n.get('care_point', '-'),
                "Full Content": n.get('content', ''), # 完整思考内容
                "Score": round(float(n.get('logic_score', 0)), 2),
                "Insight": n.get('insight', '-')
            })

    # 3. 用户表格数据准备
    rich_user_data = []
    if all_users:
        for u in all_users:
            stats = user_stats.get(u['username'], {'nodes':0, 'total_score':0})
            avg = stats['total_score'] / stats['nodes'] if stats['nodes'] > 0 else 0
            rich_user_data.append({
                "User": u['username'],
                "Nick": u['nickname'],
                "Nodes": stats['nodes'],
                "Avg Score": round(avg, 2),
                "Last Seen": u['last_seen'][:16].replace('T', ' ')
            })
    
    # === 顶部指标 ===
    k1, k2, k3, k4 = st.columns(4)
    k1.metric("Citizens", len(all_users))
    k2.metric("Nodes", len(global_nodes))
    
    avg_sys_care = 0
    if global_nodes:
        total = sum([float(n.get('logic_score', 0)) for n in global_nodes])
        avg_sys_care = total / len(global_nodes)
    k3.metric("Avg. Meaning", f"{avg_sys_care:.2f}")
    k4.metric("Engine", "Active")
    
    st.divider()
    
    # === 标签页布局 ===
    tabs = st.tabs(["🧬 Meaning Stream", "👥 Citizen Registry", "🌍 Global Pulse", "🛠️ Genesis", "⚠️ Logs"])
    
    # === Tab 1: 意义流监控 ===
    with tabs[0]:
        st.markdown("### 🧬 Real-time Meaning Stream")
        st.caption("Latest thoughts generated by the collective mind. Sorted by Time (Desc).")
        
        if node_stream_data:
            df_stream = pd.DataFrame(node_stream_data)
            st.dataframe(
                df_stream,
                use_container_width=True,
                height=600,
                hide_index=True,
                column_config={
                    "Time": st.column_config.TextColumn("Time", width="small"),
                    "User": st.column_config.TextColumn("User", width="small"),
                    "Care Point": st.column_config.TextColumn("Care Point", width="medium"),
                    "Full Content": st.column_config.TextColumn("Full Content", width="large"),
                    "Score": st.column_config.ProgressColumn("Score", min_value=0, max_value=1, format="%.2f"),
                    "Insight": st.column_config.TextColumn("AI Insight", width="medium"),
                }
            )
        else:
            st.info("The void is silent. No meaning cards generated yet.")

    # === Tab 2: 用户管理 ===
    with tabs[1]:
        c_list, c_action = st.columns([0.65, 0.35])
        
        with c_list:
            st.markdown("#### 📜 Registered Identities")
            if rich_user_data:
                df_users = pd.DataFrame(rich_user_data).sort_values(by="Last Seen", ascending=False)
                st.dataframe(
                    df_users, 
                    use_container_width=True, 
                    hide_index=True,
                    height=400,
                    column_config={
                        "Nodes": st.column_config.ProgressColumn("Nodes", min_value=0, max_value=50, format="%d"),
                        "Avg Score": st.column_config.NumberColumn("Avg Score", format="%.2f")
                    }
                )
            else:
                st.info("No citizens found.")

        with c_action:
            st.markdown("#### 🧨 Termination")
            with st.container(border=True):
                user_list = [u['username'] for u in all_users] if all_users else []
                target_user = st.selectbox("Target", user_list, index=None, placeholder="Select to Wipe...")
                confirm_nuke = st.checkbox(f"Confirm Wipe")
                
                if st.button("EXECUTE NUKE", type="primary", disabled=not (target_user and confirm_nuke)):
                    if target_user == "admin":
                        st.error("Cannot delete Architect.")
                    else:
                        with st.spinner("Erasing..."):
                            success, msg = db.nuke_user(target_user)
                            if success:
                                st.success(f"Eliminated.")
                                time.sleep(1)
                                st.rerun()
                            else:
                                st.error(f"Failed: {msg}")

    # === Tab 3: 地图 ===
    with tabs[2]:
        viz.render_cyberpunk_map(global_nodes, height="600px", is_fullscreen=False)

    # === Tab 4: 模拟器 (AI 设置增强版) ===
    with tabs[3]:
        # 上半部分：批量操作
        c_gen1, c_gen2 = st.columns(2)
        with c_gen1:
            with st.container(border=True):
                st.markdown("#### 📦 Batch Summon")
                st.caption("Randomly summon standard archetypes.")
                count_sim = st.slider("Quantity", 1, 5, 2, key="sim_qty")
                if st.button("👥 Summon Random", use_container_width=True):
                    with st.spinner("Fabricating..."):
                        sim.create_virtual_citizens(count_sim) # 假设sim库支持数量参数，或自行循环
                        st.success("Batch creation complete.")
                        time.sleep(1)
                        st.rerun()
        with c_gen2:
            with st.container(border=True):
                st.markdown("#### ⚡ Batch Injection")
                st.caption("Trigger random thoughts from existing sims.")
                count_thought = st.slider("Batch Size", 1, 5, 1, key="inj_qty")
                if st.button("💉 Inject Random", use_container_width=True, type="primary"):
                    with st.status("Simulating...", expanded=True):
                        logs = sim.inject_thoughts(count_thought)
                        for log in logs: st.text(log)
        
        st.divider()
        
        # 下半部分：自定义设计 (新增功能)
        st.markdown("#### 🔬 Laboratory: Custom Design")
        st.caption("Manually fabricate a unique Simulacrum with specific traits.")
        
        with st.expander("🧬 Open Creator Console", expanded=False):
            c_cust1, c_cust2 = st.columns([1, 1])
            with c_cust1:
                new_name = st.text_input("Designation Name", placeholder="e.g. Socrates_AI")
                new_city = st.selectbox("Origin Node", ["CyberSpace", "Tokyo", "London", "DeepSea", "Mars"])
            with c_cust2:
                st.caption("Soul Topology Parameters")
                r_care = st.slider("Care", 1, 10, 5, help="Tendency to nurture")
                r_agency = st.slider("Agency", 1, 10, 5, help="Will to power")
                r_reflection = st.slider("Reflection", 1, 10, 5, help="Depth of thought")
                r_empathy = st.slider("Empathy", 1, 10, 5, help="Resonance with others")
            
            if st.button("🧬 Fabricate Custom Soul", use_container_width=True):
                if new_name:
                    uname = f"sim_{new_name.lower().replace(' ', '_')}"
                    # 手动创建用户
                    if msc.add_user(uname, "123456", new_name, new_city):
                        # 构建自定义雷达数据
                        custom_radar = {
                            "Care": r_care, "Agency": r_agency, "Reflection": r_reflection,
                            "Empathy": r_empathy, "Curiosity": 5, "Coherence": 5, "Aesthetic": 5
                        }
                        # 更新数据库
                        msc.update_radar_score(uname, json.dumps(custom_radar))
                        st.success(f"Identity {new_name} created successfully.")
                        time.sleep(1)
                        st.rerun()
                    else:
                        st.error("Identity name conflict. Please choose another.")
                else:
                    st.warning("Designation Name required.")

    # === Tab 5: 日志 ===
    with tabs[4]:
        if st.button("Refresh Logs"): st.rerun()
        try:
            logs = msc.get_system_logs(limit=50)
            if logs: st.dataframe(pd.DataFrame(logs), use_container_width=True)
            else: st.caption("No logs available.")
        except: st.caption("Log system unavailable.")
